# Generated by Django 4.0.4 on 2022-05-23 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=100)),
                ('shortText', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='')),
                ('date', models.DateTimeField()),
                ('view_count', models.IntegerField(default=0)),
            ],
        ),
    ]
