# Generated by Django 3.2.13 on 2022-05-25 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0003_post_text_alter_post_date_alter_post_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='cat_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='postapp.categorya'),
        ),
    ]
